# Generated by Django 4.2 on 2024-06-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposition", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=256)),
                ("state", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Victim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("White", "White"),
                            ("Asian", "Asian"),
                            ("Black", "Black"),
                            ("Hispanic", "Hispanic"),
                        ],
                        max_length=256,
                    ),
                ),
                ("age", models.IntegerField(blank=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Homicide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "disposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homicides_api.disposition",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homicides_api.location",
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homicides_api.victim",
                    ),
                ),
            ],
        ),
    ]
